import type { Metadata } from "next";
import clsx from "clsx";

import { Inter } from "next/font/google";
import { ThemeProvider } from "@/providers/theme-provider";

import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "h-full")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col flex-1 h-full">
            <main className="flex-1 ">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
